// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransportPacket.proto

package cotton.network;

public final class TransportPacket {
  private TransportPacket() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cotton.network.Packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool keepalive = 1;</code>
     */
    boolean hasKeepalive();
    /**
     * <code>optional bool keepalive = 1;</code>
     */
    boolean getKeepalive();

    /**
     * <code>optional .cotton.network.Packet.PathType pathtype = 2;</code>
     */
    boolean hasPathtype();
    /**
     * <code>optional .cotton.network.Packet.PathType pathtype = 2;</code>
     */
    cotton.network.TransportPacket.Packet.PathType getPathtype();

    /**
     * <code>optional bytes data = 3;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 3;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>optional .cotton.network.Origin origin = 4;</code>
     */
    boolean hasOrigin();
    /**
     * <code>optional .cotton.network.Origin origin = 4;</code>
     */
    cotton.network.TransportPacket.Origin getOrigin();
    /**
     * <code>optional .cotton.network.Origin origin = 4;</code>
     */
    cotton.network.TransportPacket.OriginOrBuilder getOriginOrBuilder();

    /**
     * <code>repeated string path = 6;</code>
     */
    com.google.protobuf.ProtocolStringList
        getPathList();
    /**
     * <code>repeated string path = 6;</code>
     */
    int getPathCount();
    /**
     * <code>repeated string path = 6;</code>
     */
    java.lang.String getPath(int index);
    /**
     * <code>repeated string path = 6;</code>
     */
    com.google.protobuf.ByteString
        getPathBytes(int index);
  }
  /**
   * Protobuf type {@code cotton.network.Packet}
   */
  public static final class Packet extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:cotton.network.Packet)
      PacketOrBuilder {
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Packet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Packet defaultInstance;
    public static Packet getDefaultInstance() {
      return defaultInstance;
    }

    public Packet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              keepalive_ = input.readBool();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              cotton.network.TransportPacket.Packet.PathType value = cotton.network.TransportPacket.Packet.PathType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                pathtype_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              data_ = input.readBytes();
              break;
            }
            case 34: {
              cotton.network.TransportPacket.Origin.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = origin_.toBuilder();
              }
              origin_ = input.readMessage(cotton.network.TransportPacket.Origin.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(origin_);
                origin_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                path_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              path_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          path_ = path_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cotton.network.TransportPacket.internal_static_cotton_network_Packet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cotton.network.TransportPacket.internal_static_cotton_network_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cotton.network.TransportPacket.Packet.class, cotton.network.TransportPacket.Packet.Builder.class);
    }

    public static com.google.protobuf.Parser<Packet> PARSER =
        new com.google.protobuf.AbstractParser<Packet>() {
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Packet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code cotton.network.Packet.PathType}
     */
    public enum PathType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>RELAY = 0;</code>
       */
      RELAY(0, 0),
      /**
       * <code>DISCOVERY = 1;</code>
       */
      DISCOVERY(1, 1),
      /**
       * <code>SERVICE = 2;</code>
       */
      SERVICE(2, 2),
      /**
       * <code>UNKNOWN = 3;</code>
       */
      UNKNOWN(3, 3),
      /**
       * <code>NOTFOUND = 4;</code>
       */
      NOTFOUND(4, 4),
      ;

      /**
       * <code>RELAY = 0;</code>
       */
      public static final int RELAY_VALUE = 0;
      /**
       * <code>DISCOVERY = 1;</code>
       */
      public static final int DISCOVERY_VALUE = 1;
      /**
       * <code>SERVICE = 2;</code>
       */
      public static final int SERVICE_VALUE = 2;
      /**
       * <code>UNKNOWN = 3;</code>
       */
      public static final int UNKNOWN_VALUE = 3;
      /**
       * <code>NOTFOUND = 4;</code>
       */
      public static final int NOTFOUND_VALUE = 4;


      public final int getNumber() { return value; }

      public static PathType valueOf(int value) {
        switch (value) {
          case 0: return RELAY;
          case 1: return DISCOVERY;
          case 2: return SERVICE;
          case 3: return UNKNOWN;
          case 4: return NOTFOUND;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PathType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<PathType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PathType>() {
              public PathType findValueByNumber(int number) {
                return PathType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return cotton.network.TransportPacket.Packet.getDescriptor().getEnumTypes().get(0);
      }

      private static final PathType[] VALUES = values();

      public static PathType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private PathType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:cotton.network.Packet.PathType)
    }

    private int bitField0_;
    public static final int KEEPALIVE_FIELD_NUMBER = 1;
    private boolean keepalive_;
    /**
     * <code>optional bool keepalive = 1;</code>
     */
    public boolean hasKeepalive() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool keepalive = 1;</code>
     */
    public boolean getKeepalive() {
      return keepalive_;
    }

    public static final int PATHTYPE_FIELD_NUMBER = 2;
    private cotton.network.TransportPacket.Packet.PathType pathtype_;
    /**
     * <code>optional .cotton.network.Packet.PathType pathtype = 2;</code>
     */
    public boolean hasPathtype() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .cotton.network.Packet.PathType pathtype = 2;</code>
     */
    public cotton.network.TransportPacket.Packet.PathType getPathtype() {
      return pathtype_;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 3;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes data = 3;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int ORIGIN_FIELD_NUMBER = 4;
    private cotton.network.TransportPacket.Origin origin_;
    /**
     * <code>optional .cotton.network.Origin origin = 4;</code>
     */
    public boolean hasOrigin() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .cotton.network.Origin origin = 4;</code>
     */
    public cotton.network.TransportPacket.Origin getOrigin() {
      return origin_;
    }
    /**
     * <code>optional .cotton.network.Origin origin = 4;</code>
     */
    public cotton.network.TransportPacket.OriginOrBuilder getOriginOrBuilder() {
      return origin_;
    }

    public static final int PATH_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList path_;
    /**
     * <code>repeated string path = 6;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPathList() {
      return path_;
    }
    /**
     * <code>repeated string path = 6;</code>
     */
    public int getPathCount() {
      return path_.size();
    }
    /**
     * <code>repeated string path = 6;</code>
     */
    public java.lang.String getPath(int index) {
      return path_.get(index);
    }
    /**
     * <code>repeated string path = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPathBytes(int index) {
      return path_.getByteString(index);
    }

    private void initFields() {
      keepalive_ = false;
      pathtype_ = cotton.network.TransportPacket.Packet.PathType.RELAY;
      data_ = com.google.protobuf.ByteString.EMPTY;
      origin_ = cotton.network.TransportPacket.Origin.getDefaultInstance();
      path_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, keepalive_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, pathtype_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, data_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, origin_);
      }
      for (int i = 0; i < path_.size(); i++) {
        output.writeBytes(6, path_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, keepalive_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, pathtype_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, origin_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < path_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(path_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getPathList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cotton.network.TransportPacket.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cotton.network.TransportPacket.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cotton.network.TransportPacket.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cotton.network.TransportPacket.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cotton.network.TransportPacket.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cotton.network.TransportPacket.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cotton.network.TransportPacket.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cotton.network.TransportPacket.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cotton.network.TransportPacket.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cotton.network.TransportPacket.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cotton.network.TransportPacket.Packet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cotton.network.Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cotton.network.Packet)
        cotton.network.TransportPacket.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cotton.network.TransportPacket.internal_static_cotton_network_Packet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cotton.network.TransportPacket.internal_static_cotton_network_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cotton.network.TransportPacket.Packet.class, cotton.network.TransportPacket.Packet.Builder.class);
      }

      // Construct using cotton.network.TransportPacket.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getOriginFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        keepalive_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        pathtype_ = cotton.network.TransportPacket.Packet.PathType.RELAY;
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (originBuilder_ == null) {
          origin_ = cotton.network.TransportPacket.Origin.getDefaultInstance();
        } else {
          originBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        path_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cotton.network.TransportPacket.internal_static_cotton_network_Packet_descriptor;
      }

      public cotton.network.TransportPacket.Packet getDefaultInstanceForType() {
        return cotton.network.TransportPacket.Packet.getDefaultInstance();
      }

      public cotton.network.TransportPacket.Packet build() {
        cotton.network.TransportPacket.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cotton.network.TransportPacket.Packet buildPartial() {
        cotton.network.TransportPacket.Packet result = new cotton.network.TransportPacket.Packet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.keepalive_ = keepalive_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pathtype_ = pathtype_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (originBuilder_ == null) {
          result.origin_ = origin_;
        } else {
          result.origin_ = originBuilder_.build();
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          path_ = path_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.path_ = path_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cotton.network.TransportPacket.Packet) {
          return mergeFrom((cotton.network.TransportPacket.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cotton.network.TransportPacket.Packet other) {
        if (other == cotton.network.TransportPacket.Packet.getDefaultInstance()) return this;
        if (other.hasKeepalive()) {
          setKeepalive(other.getKeepalive());
        }
        if (other.hasPathtype()) {
          setPathtype(other.getPathtype());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasOrigin()) {
          mergeOrigin(other.getOrigin());
        }
        if (!other.path_.isEmpty()) {
          if (path_.isEmpty()) {
            path_ = other.path_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensurePathIsMutable();
            path_.addAll(other.path_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cotton.network.TransportPacket.Packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cotton.network.TransportPacket.Packet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean keepalive_ ;
      /**
       * <code>optional bool keepalive = 1;</code>
       */
      public boolean hasKeepalive() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool keepalive = 1;</code>
       */
      public boolean getKeepalive() {
        return keepalive_;
      }
      /**
       * <code>optional bool keepalive = 1;</code>
       */
      public Builder setKeepalive(boolean value) {
        bitField0_ |= 0x00000001;
        keepalive_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool keepalive = 1;</code>
       */
      public Builder clearKeepalive() {
        bitField0_ = (bitField0_ & ~0x00000001);
        keepalive_ = false;
        onChanged();
        return this;
      }

      private cotton.network.TransportPacket.Packet.PathType pathtype_ = cotton.network.TransportPacket.Packet.PathType.RELAY;
      /**
       * <code>optional .cotton.network.Packet.PathType pathtype = 2;</code>
       */
      public boolean hasPathtype() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .cotton.network.Packet.PathType pathtype = 2;</code>
       */
      public cotton.network.TransportPacket.Packet.PathType getPathtype() {
        return pathtype_;
      }
      /**
       * <code>optional .cotton.network.Packet.PathType pathtype = 2;</code>
       */
      public Builder setPathtype(cotton.network.TransportPacket.Packet.PathType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        pathtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .cotton.network.Packet.PathType pathtype = 2;</code>
       */
      public Builder clearPathtype() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pathtype_ = cotton.network.TransportPacket.Packet.PathType.RELAY;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 3;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes data = 3;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 3;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 3;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private cotton.network.TransportPacket.Origin origin_ = cotton.network.TransportPacket.Origin.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          cotton.network.TransportPacket.Origin, cotton.network.TransportPacket.Origin.Builder, cotton.network.TransportPacket.OriginOrBuilder> originBuilder_;
      /**
       * <code>optional .cotton.network.Origin origin = 4;</code>
       */
      public boolean hasOrigin() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .cotton.network.Origin origin = 4;</code>
       */
      public cotton.network.TransportPacket.Origin getOrigin() {
        if (originBuilder_ == null) {
          return origin_;
        } else {
          return originBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .cotton.network.Origin origin = 4;</code>
       */
      public Builder setOrigin(cotton.network.TransportPacket.Origin value) {
        if (originBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          origin_ = value;
          onChanged();
        } else {
          originBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .cotton.network.Origin origin = 4;</code>
       */
      public Builder setOrigin(
          cotton.network.TransportPacket.Origin.Builder builderForValue) {
        if (originBuilder_ == null) {
          origin_ = builderForValue.build();
          onChanged();
        } else {
          originBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .cotton.network.Origin origin = 4;</code>
       */
      public Builder mergeOrigin(cotton.network.TransportPacket.Origin value) {
        if (originBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              origin_ != cotton.network.TransportPacket.Origin.getDefaultInstance()) {
            origin_ =
              cotton.network.TransportPacket.Origin.newBuilder(origin_).mergeFrom(value).buildPartial();
          } else {
            origin_ = value;
          }
          onChanged();
        } else {
          originBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .cotton.network.Origin origin = 4;</code>
       */
      public Builder clearOrigin() {
        if (originBuilder_ == null) {
          origin_ = cotton.network.TransportPacket.Origin.getDefaultInstance();
          onChanged();
        } else {
          originBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .cotton.network.Origin origin = 4;</code>
       */
      public cotton.network.TransportPacket.Origin.Builder getOriginBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getOriginFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .cotton.network.Origin origin = 4;</code>
       */
      public cotton.network.TransportPacket.OriginOrBuilder getOriginOrBuilder() {
        if (originBuilder_ != null) {
          return originBuilder_.getMessageOrBuilder();
        } else {
          return origin_;
        }
      }
      /**
       * <code>optional .cotton.network.Origin origin = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          cotton.network.TransportPacket.Origin, cotton.network.TransportPacket.Origin.Builder, cotton.network.TransportPacket.OriginOrBuilder> 
          getOriginFieldBuilder() {
        if (originBuilder_ == null) {
          originBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              cotton.network.TransportPacket.Origin, cotton.network.TransportPacket.Origin.Builder, cotton.network.TransportPacket.OriginOrBuilder>(
                  getOrigin(),
                  getParentForChildren(),
                  isClean());
          origin_ = null;
        }
        return originBuilder_;
      }

      private com.google.protobuf.LazyStringList path_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePathIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          path_ = new com.google.protobuf.LazyStringArrayList(path_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string path = 6;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPathList() {
        return path_.getUnmodifiableView();
      }
      /**
       * <code>repeated string path = 6;</code>
       */
      public int getPathCount() {
        return path_.size();
      }
      /**
       * <code>repeated string path = 6;</code>
       */
      public java.lang.String getPath(int index) {
        return path_.get(index);
      }
      /**
       * <code>repeated string path = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPathBytes(int index) {
        return path_.getByteString(index);
      }
      /**
       * <code>repeated string path = 6;</code>
       */
      public Builder setPath(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePathIsMutable();
        path_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string path = 6;</code>
       */
      public Builder addPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePathIsMutable();
        path_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string path = 6;</code>
       */
      public Builder addAllPath(
          java.lang.Iterable<java.lang.String> values) {
        ensurePathIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, path_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string path = 6;</code>
       */
      public Builder clearPath() {
        path_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string path = 6;</code>
       */
      public Builder addPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePathIsMutable();
        path_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cotton.network.Packet)
    }

    static {
      defaultInstance = new Packet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:cotton.network.Packet)
  }

  public interface OriginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cotton.network.Origin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string latchId = 1;</code>
     */
    boolean hasLatchId();
    /**
     * <code>optional string latchId = 1;</code>
     */
    java.lang.String getLatchId();
    /**
     * <code>optional string latchId = 1;</code>
     */
    com.google.protobuf.ByteString
        getLatchIdBytes();

    /**
     * <code>optional string requestId = 2;</code>
     */
    boolean hasRequestId();
    /**
     * <code>optional string requestId = 2;</code>
     */
    java.lang.String getRequestId();
    /**
     * <code>optional string requestId = 2;</code>
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    /**
     * <code>optional string ip = 3;</code>
     */
    boolean hasIp();
    /**
     * <code>optional string ip = 3;</code>
     */
    java.lang.String getIp();
    /**
     * <code>optional string ip = 3;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>optional int32 port = 4;</code>
     */
    boolean hasPort();
    /**
     * <code>optional int32 port = 4;</code>
     */
    int getPort();
  }
  /**
   * Protobuf type {@code cotton.network.Origin}
   */
  public static final class Origin extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:cotton.network.Origin)
      OriginOrBuilder {
    // Use Origin.newBuilder() to construct.
    private Origin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Origin(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Origin defaultInstance;
    public static Origin getDefaultInstance() {
      return defaultInstance;
    }

    public Origin getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Origin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              latchId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              requestId_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              ip_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              port_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cotton.network.TransportPacket.internal_static_cotton_network_Origin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cotton.network.TransportPacket.internal_static_cotton_network_Origin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cotton.network.TransportPacket.Origin.class, cotton.network.TransportPacket.Origin.Builder.class);
    }

    public static com.google.protobuf.Parser<Origin> PARSER =
        new com.google.protobuf.AbstractParser<Origin>() {
      public Origin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Origin(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Origin> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int LATCHID_FIELD_NUMBER = 1;
    private java.lang.Object latchId_;
    /**
     * <code>optional string latchId = 1;</code>
     */
    public boolean hasLatchId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string latchId = 1;</code>
     */
    public java.lang.String getLatchId() {
      java.lang.Object ref = latchId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          latchId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string latchId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLatchIdBytes() {
      java.lang.Object ref = latchId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        latchId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTID_FIELD_NUMBER = 2;
    private java.lang.Object requestId_;
    /**
     * <code>optional string requestId = 2;</code>
     */
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string requestId = 2;</code>
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string requestId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 3;
    private java.lang.Object ip_;
    /**
     * <code>optional string ip = 3;</code>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string ip = 3;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ip = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 4;
    private int port_;
    /**
     * <code>optional int32 port = 4;</code>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 port = 4;</code>
     */
    public int getPort() {
      return port_;
    }

    private void initFields() {
      latchId_ = "";
      requestId_ = "";
      ip_ = "";
      port_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getLatchIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRequestIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getIpBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, port_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getLatchIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRequestIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getIpBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, port_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cotton.network.TransportPacket.Origin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cotton.network.TransportPacket.Origin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cotton.network.TransportPacket.Origin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cotton.network.TransportPacket.Origin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cotton.network.TransportPacket.Origin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cotton.network.TransportPacket.Origin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cotton.network.TransportPacket.Origin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cotton.network.TransportPacket.Origin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cotton.network.TransportPacket.Origin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cotton.network.TransportPacket.Origin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cotton.network.TransportPacket.Origin prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cotton.network.Origin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cotton.network.Origin)
        cotton.network.TransportPacket.OriginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cotton.network.TransportPacket.internal_static_cotton_network_Origin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cotton.network.TransportPacket.internal_static_cotton_network_Origin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cotton.network.TransportPacket.Origin.class, cotton.network.TransportPacket.Origin.Builder.class);
      }

      // Construct using cotton.network.TransportPacket.Origin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        latchId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        requestId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cotton.network.TransportPacket.internal_static_cotton_network_Origin_descriptor;
      }

      public cotton.network.TransportPacket.Origin getDefaultInstanceForType() {
        return cotton.network.TransportPacket.Origin.getDefaultInstance();
      }

      public cotton.network.TransportPacket.Origin build() {
        cotton.network.TransportPacket.Origin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cotton.network.TransportPacket.Origin buildPartial() {
        cotton.network.TransportPacket.Origin result = new cotton.network.TransportPacket.Origin(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.latchId_ = latchId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.requestId_ = requestId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.port_ = port_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cotton.network.TransportPacket.Origin) {
          return mergeFrom((cotton.network.TransportPacket.Origin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cotton.network.TransportPacket.Origin other) {
        if (other == cotton.network.TransportPacket.Origin.getDefaultInstance()) return this;
        if (other.hasLatchId()) {
          bitField0_ |= 0x00000001;
          latchId_ = other.latchId_;
          onChanged();
        }
        if (other.hasRequestId()) {
          bitField0_ |= 0x00000002;
          requestId_ = other.requestId_;
          onChanged();
        }
        if (other.hasIp()) {
          bitField0_ |= 0x00000004;
          ip_ = other.ip_;
          onChanged();
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cotton.network.TransportPacket.Origin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cotton.network.TransportPacket.Origin) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object latchId_ = "";
      /**
       * <code>optional string latchId = 1;</code>
       */
      public boolean hasLatchId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string latchId = 1;</code>
       */
      public java.lang.String getLatchId() {
        java.lang.Object ref = latchId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            latchId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string latchId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLatchIdBytes() {
        java.lang.Object ref = latchId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          latchId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string latchId = 1;</code>
       */
      public Builder setLatchId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        latchId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string latchId = 1;</code>
       */
      public Builder clearLatchId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        latchId_ = getDefaultInstance().getLatchId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string latchId = 1;</code>
       */
      public Builder setLatchIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        latchId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object requestId_ = "";
      /**
       * <code>optional string requestId = 2;</code>
       */
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string requestId = 2;</code>
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            requestId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string requestId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string requestId = 2;</code>
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestId = 2;</code>
       */
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestId = 2;</code>
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        requestId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>optional string ip = 3;</code>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string ip = 3;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ip_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ip = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ip = 3;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 3;</code>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 3;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ip_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>optional int32 port = 4;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 port = 4;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>optional int32 port = 4;</code>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000008;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 port = 4;</code>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000008);
        port_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cotton.network.Origin)
    }

    static {
      defaultInstance = new Origin(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:cotton.network.Origin)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cotton_network_Packet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cotton_network_Packet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cotton_network_Origin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cotton_network_Origin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025TransportPacket.proto\022\016cotton.network\"" +
      "\340\001\n\006Packet\022\021\n\tkeepalive\030\001 \001(\010\0221\n\010pathtyp" +
      "e\030\002 \001(\0162\037.cotton.network.Packet.PathType" +
      "\022\014\n\004data\030\003 \001(\014\022&\n\006origin\030\004 \001(\0132\026.cotton." +
      "network.Origin\022\014\n\004path\030\006 \003(\t\"L\n\010PathType" +
      "\022\t\n\005RELAY\020\000\022\r\n\tDISCOVERY\020\001\022\013\n\007SERVICE\020\002\022" +
      "\013\n\007UNKNOWN\020\003\022\014\n\010NOTFOUND\020\004\"F\n\006Origin\022\017\n\007" +
      "latchId\030\001 \001(\t\022\021\n\trequestId\030\002 \001(\t\022\n\n\002ip\030\003" +
      " \001(\t\022\014\n\004port\030\004 \001(\005B\021B\017TransportPacket"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cotton_network_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cotton_network_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cotton_network_Packet_descriptor,
        new java.lang.String[] { "Keepalive", "Pathtype", "Data", "Origin", "Path", });
    internal_static_cotton_network_Origin_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cotton_network_Origin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cotton_network_Origin_descriptor,
        new java.lang.String[] { "LatchId", "RequestId", "Ip", "Port", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
